name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker Login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        DOCKER_TOKEN: ${{secrets.DOCKER_TOKEN}}
      run: echo $DOCKER_TOKEN | docker login -u $DOCKER_USER
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag luri/node:$(date +%s)
    - name: Docker Logout
      run: docker logout
