name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: docker/login-action@v1
    - name: Docker Login
      with:
        username: ${{secrets.DOCKER_USER}}
        password: ${{secrets.DOCKER_PASSWORD}}
        token: ${{secrets.DOCKER_TOKEN}}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag luri/node:$(date +%s)
    - name: Docker Logout
      run: docker logout
